map:
  general:
    world_frame: "odom"
    thresholding_period: { seconds: 2.0 }
    pruning_period: { seconds: 10.0 }
    publication_period: { seconds: 2.0 }
  data_structure:
    type: hashed_chunked_wavelet_octree
    min_cell_width: { meters: 0.03 }

# depth_camera_front_lower
inputs:
  - type: depth_image
    general:
      topic_name: "/depth_camera_front_lower/depth/image_rect_raw"
      depth_scale_factor: 0.001
      topic_queue_length: 1
      max_wait_for_pose: { seconds: 1.0 }
      time_offset: { seconds: -0.025 }
    integrators:
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 0.3 }
          max_range: { meters: 1.0 }
          termination_update_error: 0.1
          termination_height: 0
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 427.0570373535156
          fy: 427.0570373535156
          cx: 407.53546142578125
          cy: 236.9319305419922
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.005 }
          scaling_free: 0.2
          scaling_occupied: 0.4
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 1.0 }
          max_range: { meters: 6.0 }
          termination_update_error: 0.1
          termination_height: 1
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 427.0570373535156
          fy: 427.0570373535156
          cx: 407.53546142578125
          cy: 236.9319305419922
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.03 }
          scaling_free: 0.2
          scaling_occupied: 0.4

# depth_camera_front_upper
inputs:
  - type: depth_image
    general:
      topic_name: "/depth_camera_front_upper/depth/image_rect_raw"
      depth_scale_factor: 0.001
      topic_queue_length: 1
      max_wait_for_pose: { seconds: 1.0 }
      time_offset: { seconds: -0.025 }
    integrators:
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 0.3 }
          max_range: { meters: 1.0 }
          termination_update_error: 0.1
          termination_height: 0
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 424.9310302734375
          fy: 424.9310302734375
          cx: 425.49896240234375
          cy: 240.00094604492188
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.005 }
          scaling_free: 0.2
          scaling_occupied: 0.4
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 1.0 }
          max_range: { meters: 6.0 }
          termination_update_error: 0.1
          termination_height: 1
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 424.9310302734375
          fy: 424.9310302734375
          cx: 425.49896240234375
          cy: 240.00094604492188
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.03 }
          scaling_free: 0.2
          scaling_occupied: 0.4

# depth_camera_rear_lower
inputs:
  - type: depth_image
    general:
      topic_name: "/depth_camera_rear_lower/depth/image_rect_raw"
      depth_scale_factor: 0.001
      topic_queue_length: 1
      max_wait_for_pose: { seconds: 1.0 }
      time_offset: { seconds: -0.025 }
    integrators:
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 0.3 }
          max_range: { meters: 1.0 }
          termination_update_error: 0.1
          termination_height: 0
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 418.2395935058594
          fy: 418.2395935058594
          cx: 419.311767578125
          cy: 241.22569274902344
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.005 }
          scaling_free: 0.2
          scaling_occupied: 0.4
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 1.0 }
          max_range: { meters: 6.0 }
          termination_update_error: 0.1
          termination_height: 1
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 418.2395935058594
          fy: 418.2395935058594
          cx: 419.311767578125
          cy: 241.22569274902344
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.03 }
          scaling_free: 0.2
          scaling_occupied: 0.4

# depth_camera_rear_upper
inputs:
  - type: depth_image
    general:
      topic_name: "/depth_camera_rear_upper/depth/image_rect_raw"
      depth_scale_factor: 0.001
      topic_queue_length: 1
      max_wait_for_pose: { seconds: 1.0 }
      time_offset: { seconds: -0.025 }
    integrators:
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 0.3 }
          max_range: { meters: 1.0 }
          termination_update_error: 0.1
          termination_height: 0
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 419.66302490234375
          fy: 419.66302490234375
          cx: 425.7276611328125
          cy: 238.27206420898438
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.005 }
          scaling_free: 0.2
          scaling_occupied: 0.4
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 1.0 }
          max_range: { meters: 6.0 }
          termination_update_error: 0.1
          termination_height: 1
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 419.66302490234375
          fy: 419.66302490234375
          cx: 425.7276611328125
          cy: 238.27206420898438
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.03 }
          scaling_free: 0.2
          scaling_occupied: 0.4

# depth_camera_left

# depth_camera_right

# dynaarm_REALSENSE
# TODO: ADD, CURRENTLY NO TRANSFORM FROM ODOM TO CAMERA
# inputs:
#   - type: depth_image
#     general:
#       topic_name: "/dynaarm_REALSENSE/aligned_depth_to_color/image_raw"
#       depth_scale_factor: 0.001
#       topic_queue_length: 1
#       max_wait_for_pose: { seconds: 1.0 }
#       time_offset: { seconds: -0.025 }
#     integrators:
#       - integration_method:
#           type: hashed_chunked_wavelet_integrator
#           min_range: { meters: 1.5 }
#           max_range: { meters: 6.0 }
#           termination_update_error: 0.1
#           termination_height: 1
#         projection_model:
#           type: pinhole_camera_projector
#           width: 640
#           height: 480
#           fx: 598.7864990234375
#           fy: 599.3023071289062
#           cx: 320.1333923339844
#           cy: 241.13986206054688
#         measurement_model:
#           type: continuous_ray
#           range_sigma: { meters: 0.03 }
#           scaling_free: 0.2
#           scaling_occupied: 0.4
